Ext.define("core.oa.view.BorrowForm",{
	extend:"Ext.form.Panel",
	alias:"widget.borrowform",
		layout : {
				type : "table",
				columns : 2
			},
	id:"borrowform",
	align:"left",
	defaults:{
			margin:"10 0 0 15",
			selectOnFocus:true,
			width:300,
			msgTarget:"side" //提示信息现在的位置
		},
	tbar:[{
			xtype:"button",
				ref:"save",
				iconCls:"table_save",
				text:"保存"
			},{
				xtype:"button",
				ref:"wfEnd",
				iconCls:"wfend",
				text:"撤销",
				hidden:true
			},{
				xtype:"button",
				ref:"wfReturn",
				iconCls:"wfreturn",
				text:"取回",
				hidden:true
			},{
				xtype:"button",
				ref:"wfBack",
				iconCls:"wfback",
				text:"回退",
				hidden:true
			},{
				xtype:"button",
				ref:"wfNext",
				iconCls:"wfnext",
				text:"送交",
				hidden:true
			},{
				xtype:"button",
				ref:"wfTake",
				iconCls:"wftake",
				text:"处理任务",
				hidden:true
			},{
				xtype:"button",
				ref:"return",
				iconCls:"return",
				text:"返回"
			},{
				xtype:"button",
				ref:"wfStart",
				iconCls:"wfstart",
				text:"启动借款申请流程",
				hidden:true
			},{
				xtype:"displayfield",
				value:"流程已经结束",
				hidden:true
			}],
	items:[{
			xtype:"textfield",
				fieldLabel:"主键",
				name:"id",
				hidden:true
			},{
				xtype:"textfield",
				fieldLabel:"申请人",
				name:"createUser",
				readOnly:true
			},{
				xtype:"textfield",
				fieldLabel:"申请人编码",
				name:"createUserCode",
				readOnly:true
			},{
				xtype:"textfield",
				fieldLabel:"所属部门",
				name:"createDept",
				readOnly:true
			},{
				xtype:"textfield",
				fieldLabel:"所属部门编码",
				name:"createDeptCode",
				readOnly:true
			},{
				xtype:"numberfield",
				fieldLabel:"申请金额",
				name:"money",
				value:0
			},{
				xtype:"textfield",
				fieldLabel:"申请时间",
				name:"createTime",
				readOnly:true
			},{
				xtype:"textareafield",
				fieldLabel:"借款理由",
				name:"jieYou",
				width:620,
				colspan: 2
			},{
				xtype:"textareafield",
				fieldLabel:"流程定义ID",
				name:"pdid",
				hidden:true
			},{
				xtype:"textareafield",
				fieldLabel:"流程实例ID",
				name:"piid",
				hidden:true
			},{
				xtype:"textareafield",
				fieldLabel:"流程状态",
				name:"status",
				hidden:true
			}],
	initComponent:function(){
		this.callParent(arguments);
	}
});